rabbitmq:
  protocol: amqps
  host: rat-01.rmq2.cloudamqp.com
  port: 5671
  auth:
    username: behwkouw
    password: nUf7oUYDZDVg5btim2WU1k6UaoycdHnR
database:
  name: portalz_admin
  host: portalz.c3ihfg6pfre6.eu-west-3.rds.amazonaws.com
  port: 5432
  auth:
    username: postgres
    password: Bn7ri5cSv86G4Ub5SzjoWPM
github:
  token: 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

RUST_LOG: info